[package]
name = "vollibrespot"
version = "0.0.1"
authors = ["ashthespy <https://github.com/ashthespy/>"]
build = "build.rs"

[[bin]]
name = "vollibrespot"
path = "src/main.rs"
doc = false

[dependencies]
env_logger = "0.5.10"
futures = "0.1.23"
getopts = "0.2.14"
hyper = "0.11.2"
log = "^0.4.0"
rpassword = "0.3.0"
tokio-core = "0.1.2"
tokio-io = "0.1"
tokio-signal = "0.1.2"
url = "1.7.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
sha-1 = "0.7.0"
hex = "0.3.2"

[build-dependencies]
vergen = "~0.1.0"

[dependencies.librespot]
git = "https://github.com/ashthespy/librespot"
branch="vollibrespot"
# path = "../librespot"
default-features = false
features = ["alsa-backend"]
