[package]
name = "vollibrespot"
version = "0.0.1"
authors = ["ashthespy <https://github.com/ashthespy/>"]
build = "build.rs"

[[bin]]
name = "vollibrespot"
path = "src/main.rs"
doc = false

[dependencies]
env_logger = "0.5.10"
futures = "0.1.23"
getopts = "0.2.14"
hyper = "0.11.2"
log = "^0.4.0"
rpassword = "0.3.0"
rust-crypto = "0.2.36"
tokio-core = "0.1.2"
tokio-io = "0.1"
tokio-signal = "0.1.2"
url = "1.7.0"
serde_json = "1.0.22"

[build-dependencies]
vergen = "~0.1.0"

[replace]
"rust-crypto:0.2.36" = { git = "https://github.com/awmath/rust-crypto.git", branch = "avx2" }

[dependencies.librespot]
# git = "https://github.com/ashthespy/librespot"
# branch="devEvents"
path = "../librespot"
default-features = false
features = ["alsa-backend"]
