version: 2

dockerparams: &dockerparams
  docker:
    - image: ashthespy/rustcross
      environment:
        CLIENT_ID: $CLIENT_ID
      auth:
        username: ashthespy
        password: $DOCKERHUB_P

jobs:
  build:
    <<: *dockerparams
    steps:
      - checkout
      - restore_cache:
          keys:
            - cargo-cache-{{ .Environment.cache_ver }}
      - run:
          name: Compile
          command: |
            cargo build --verbose
            /build/debug/vollibrespot --version
            /build/debug/vollibrespot --version > version
      - persist_to_workspace:
          root: .
          paths: version
      - save_cache:
          key: cargo-cache-{{ .Environment.cache_ver }}
          paths:
            - "/build/cache"

  cross-armv7l:
    <<: *dockerparams
    steps:
      - checkout
      - restore_cache:
          keys:
            - cargo-cache-{{ .Environment.cache_ver }}
            - cargo-build-armv7-unknown-linux-gnueabihf-{{ .Environment.cache_ver }}
      - run:
          name: cross-armv7l
          command: |
            cargo build --release --target armv7-unknown-linux-gnueabihf &&
            tar czf vollibrespot-armv7l.tar.xz \
              -C /build/armv7-unknown-linux-gnueabihf/release/ vollibrespot
      - store_artifacts:
          path: ./vollibrespot-armv7l.tar.xz
          destination: vollibrespot-armv7l.tar.xz
      - persist_to_workspace:
          root: .
          paths: '*.tar*'
      - save_cache:
          key: cargo-build-armv7-unknown-linux-gnueabihf-{{ .Environment.cache_ver }}
          paths:
            - "/build/armv7-unknown-linux-gnueabihf"

  cross-armv6l:
    <<: *dockerparams
    steps:
      - checkout
      - restore_cache:
          keys:
            - cargo-cache-{{ .Environment.cache_ver }}
            - cargo-build-arm-unknown-linux-gnueabihf-{{ .Environment.cache_ver }}
      - run:
          name: cross-armv6l
          command: |
            cargo build --release --target arm-unknown-linux-gnueabihf &&
            tar czf vollibrespot-armv6l.tar.xz \
              -C /build/arm-unknown-linux-gnueabihf/release/ vollibrespot
      - store_artifacts:
          path: ./vollibrespot-armv6l.tar.xz
          destination: vollibrespot-armv6l.tar.xz
      - persist_to_workspace:
          root: .
          paths: '*.tar*'
      - save_cache:
          key: cargo-build-arm-unknown-linux-gnueabihf-{{ .Environment.cache_ver }}
          paths:
            - "/build/arm-unknown-linux-gnueabihf"

  cross-aarch64:
    <<: *dockerparams
    steps:
      - checkout
      - restore_cache:
          keys:
            - cargo-cache-{{ .Environment.cache_ver }}
            - cargo-build-aarch64-unknown-linux-gnu-{{ .Environment.cache_ver }}
      - run:
          name: cross-aarch64
          command: |
            cargo build --release --target aarch64-unknown-linux-gnu &&
            tar czf vollibrespot-aarch64.tar.xz \
              -C /build/aarch64-unknown-linux-gnu/release/ vollibrespot
      - store_artifacts:
          path: ./vollibrespot-aarch64.tar.xz
          destination: vollibrespot-aarch64.tar.xz
      - persist_to_workspace:
          root: .
          paths: '*.tar*'
      - save_cache:
          key: cargo-build-aarch64-unknown-linux-gnu-{{ .Environment.cache_ver }}
          paths:
            - "/build/aarch64-unknown-linux-gnu"

  cross-i686:
    <<: *dockerparams
    steps:
      - checkout
      - restore_cache:
          keys:
            - cargo-cache-{{ .Environment.cache_ver }}
            - cargo-build-i686-unknown-linux-gnu-{{ .Environment.cache_ver }}
      - run:
          name: cross-i686
          command: |
            apt-get install -y gcc-multilib &&
            cargo build --release --target i686-unknown-linux-gnu &&
            tar czf vollibrespot-i686.tar.xz \
              -C /build/i686-unknown-linux-gnu/release/ vollibrespot
      - store_artifacts:
          path: ./vollibrespot-i686.tar.xz
          destination: vollibrespot-i686.tar.xz
      - persist_to_workspace:
          root: .
          paths: '*.tar*'
      - save_cache:
          key: cargo-build-i686-unknown-linux-gnu-{{ .Environment.cache_ver }}
          paths:
            - "/build/i686-unknown-linux-gnu"

  publish-release:
    docker:
      - image: cibuilds/github:0.12
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: github-release
          command: |
            VERSION=$(git describe --always)
            echo -e $(git log -1 --format="%h %s (%cd)") >> ./version
            echo ${VERSION} >> ./version
            ls -l *.tar* >> ./version
            mkdir ./Release && mv ./version ./Release
            mv *.tar* ./Release
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r \
            ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} \
            -n ${VERSION} -draft -delete ${VERSION} ./Release
      - store_artifacts:
          path: ./Release
          destination: Release

workflows:
  version: 2
  build_and_crosscompile:
    jobs:
      - build
      - cross-armv7l:
          requires:
            - build
      - cross-armv6l:
          requires:
            - build
      - cross-aarch64:
          requires:
            - build
      - cross-i686:
          requires:
            - build
      - publish-release:
          requires:
            - cross-armv7l
            - cross-armv6l
            - cross-aarch64
            - cross-i686
          # filters:
          #   tags:
          #     only: /^v\d+\.\d+\.\d+$/
